// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhbIp7F5sSB_gsUNhCQ9zF6_nTdjp_bI',
    appId: '1:377469784644:web:1ec055a921a1c06174e211',
    messagingSenderId: '377469784644',
    projectId: 'inlo-1264a',
    authDomain: 'inlo-1264a.firebaseapp.com',
    storageBucket: 'inlo-1264a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9zyte-XSnoV5T5IdTf-YN5ZgmkvG9HEQ',
    appId: '1:377469784644:android:d3db3e5133131bd274e211',
    messagingSenderId: '377469784644',
    projectId: 'inlo-1264a',
    storageBucket: 'inlo-1264a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqNInNWp4BeThi4DxgNwlgqIu82VaMptA',
    appId: '1:377469784644:ios:f3d7fa1ec7b51acb74e211',
    messagingSenderId: '377469784644',
    projectId: 'inlo-1264a',
    storageBucket: 'inlo-1264a.firebasestorage.app',
    iosBundleId: 'com.example.inlo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqNInNWp4BeThi4DxgNwlgqIu82VaMptA',
    appId: '1:377469784644:ios:f3d7fa1ec7b51acb74e211',
    messagingSenderId: '377469784644',
    projectId: 'inlo-1264a',
    storageBucket: 'inlo-1264a.firebasestorage.app',
    iosBundleId: 'com.example.inlo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzhbIp7F5sSB_gsUNhCQ9zF6_nTdjp_bI',
    appId: '1:377469784644:web:0035f83f3308165f74e211',
    messagingSenderId: '377469784644',
    projectId: 'inlo-1264a',
    authDomain: 'inlo-1264a.firebaseapp.com',
    storageBucket: 'inlo-1264a.firebasestorage.app',
  );
}
